[workspace]
members = [
    "hello_world",
    "chpt3/temp_conversion",
    "chpt3/fibonacci",
    "chpt4/ownership",
    "chpt4/slices",
    "chpt5/structs",
    "chpt6/enums",
    "chpt6/patterns",
    "chpt8/vec",
    "chpt8/string",
    "chpt8/hashmap",
    "chpt8/prob1"
]
